services:
- type: web
  name: image-classification-api
  env: python
  plan: free
  autoDeploy: true
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
  envVars:
  - key: PYTHON_VERSION
    value: 3.9
  - key: FLASK_ENV
    value: production